### PR TITLE
Add event for extend product list toolbar

### PR DESCRIPTION
**Pull request by m49n**

### CODE REVIEW

**Comment by kharanenka** [comment]
Hi! Thanks for your contribution. I will merge PR later. It will be useful for us to add some events to all controllers.

**Comment by SebastiaanKloos** [comment]
I'm working on a plugin where this feature is also needed. So a big plus one from me. Hope the events will be added to the plugin soon!

**Comment by web-studio-51** [comment]
Hi! Skolko let jdat prinyatia plugina?

**Review by kharanenka — APPROVED** [review]

**Comment by kharanenka** [comment]
Thanks for your contribution

**Pull request merged**
