### PR TITLE
Allow negative offer quantity

### PR DESCRIPTION
**Pull request by SebastiaanKloos**
Added the functionality to allow negative offer quantities

### CODE REVIEW

**Comment by SebastiaanKloos** [comment]
I've added some languages right now. Do I need to add the English translation to the other languages?

I've added nl, en, ru right now

**Comment by SebastiaanKloos** [comment]
There is a little bug. Need to remove "unsigned" from the quantity attribute

**Review by kharanenka — APPROVED** [review]

**Comment by kharanenka** [comment]
Thanks for your contribution

**Comment by SebastiaanKloos** [comment]
Thank you so much for merging the code!

**Pull request merged**
